// Token error constants
const TOKEN_ERRORS = {
    MISSING_REFRESH: 'MISSING_REFRESH_TOKEN',
    INVALID_REFRESH: 'INVALID_REFRESH_TOKEN',
    EXPIRED_REFRESH: 'EXPIRED_REFRESH_TOKEN',
    MISSING_ACCESS: 'MISSING_ACCESS_TOKEN',
    INVALID_ACCESS: 'INVALID_ACCESS_TOKEN',
    EXPIRED_ACCESS: 'EXPIRED_ACCESS_TOKEN',
};

export default TOKEN_ERRORS;
